### ISSUE TITLE
Hi Ruben please help thanks

### ISSUE THREAD

**Issue by nmars-cloud** [rubenhortas/awesome-ip-widget#2] opened 2023-08-05 13:27 UTC
hi ruben i have question for you i have manjaro linux awesome wm from arco linux my schemat is /home/nmars/.config/awesome/lain/widget/ and your awesome ip widget doesnt work unexpeted symbol near say massage please help thank you

**Comment by rubenhortas** [comment] 2023-08-07 20:19
Hi, @nmars-cloud

I'm currently using it in awesome 4.3-4 and lua 5.1.5-9.

"_unexpected symbol_" means there's an syntax error in the file. A syntax error is a mistake in the file, for example a missing or duplicate character (comma, quotation mark, parentheses, bracket...) a misspelled word, an extra character in a line (some editors add these types of characters) or even a bad path. First, check that your `rc.lua` file doesn't have these type of errors. You can comment (or remove) the lines related to the widget to rule out that the error is in another part of the file.

Also, try a "default" installation, using the paths specified in the [README.MD](https://github.com/rubenhortas/awesome-ip-widget/blob/main/README.md), you can always change them later. Clone the widget in `/home/nmars/.config/awesome/widgets`. You should have the widget in `/home/nmars/.config/awesome/widgets/awesome-ip-widget`. Then edit your `~/.config/awesome/rc.lua` as the [README.MD](https://github.com/rubenhortas/awesome-ip-widget/blob/main/README.md) says, and add the widget in the section you prefer, for example, to add it to the widgets on the right:

* Add this under the other `local ... = ...` lines. Before the `-- {{{ Error handling` line and make sure the quotes and parentheses are closed and not repeated.

```lua
local ip_widget = require("widgets.awesome-ip-widget.ip")
```

(I corrected this line in the  [README.MD](https://github.com/rubenhortas/awesome-ip-widget/blob/main/README.md), it was missing the "_widgets._" part.)

* Add the widget in your preferred position and make sure that there's a comma after the widget name. For example, to add it to the widgets on the right:

```lua
s.mytasklist, -- Middle widget
{ -- Right widgets
  layout = wibox.layout.fixed.horizontal,
	ip_widget,
},
```

* Configure the widget. Edit `awesome-ip-widget/ip.lua`. Replace `enp0s3` with your interface name and make sure the quotes are closed and not repeated:

```lua
local interface = "enp0s3"
``` 

* Reset awesome and should work.

If you want to keep `/home/nmars/.config/awesome/lain/widget/` as path, you should have to adjust the `require` line. I think you should use:

```lua
local ip_widget = require("lain.widget.awesome-ip-widget.ip")
```

The error could be due to this line. As I said, I corrected the [README.MD](https://github.com/rubenhortas/awesome-ip-widget/blob/main/README.md), it was missing the "_widgets._" part, and you are using a totally different path, so the require could be failing.

If you solve the error let me know to close this issue.
If you don't solve the error let me know also. You also can paste your error and your `rc.lua`, and let's see if we find the cause.

I hope I've helped! :)

**Comment by nmars-cloud** [comment] 2023-08-07 23:52
hi again ruben i understand everything you wrote please read my rc lua i paste it here https://ufile.io/rcme47ge thanks for help

**Comment by nmars-cloud** [comment] 2023-08-08 16:41
nevermind i figure it out thanks for help

**Comment by rubenhortas** [comment] 2023-08-08 18:59
Great to hear. I'm going to close the issue.
You're welcome ☺️

**Closed as completed by rubenhortas** 2023-08-08 18:59 UTC
Labels: help wanted
